// Generate `src/styles.generated.ts` — the compiled CSS the custom element
// inlines into its shadow root. It concatenates the two compiled stylesheets a
// wrapped Editor needs (both are authored against global `.pfdjs-*` classes and
// ship only as compiled `dist/style.css`, so we read the built output rather
// than re-authoring SCSS):
//   - @d3-polytree/editor/style.css            (properties panel + palette + drag)
//   - @d3-polytree/interactive-viewer/style.css (outline + notifications + side-tabs + search)
// Committed to the repo (like icons-amazon's icons.generated.ts) so `tsc`/tsup
// find it without running this step; regenerated by the package `build` before
// tsup, and turbo `^build` guarantees the upstream dist CSS exists first.
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const require = createRequire(import.meta.url);

function readPackageCss(pkg) {
  const cssPath = require.resolve(`${pkg}/style.css`);
  return readFileSync(cssPath, 'utf8');
}

const editorCss = readPackageCss('@d3-polytree/editor');
const interactiveViewerCss = readPackageCss('@d3-polytree/interactive-viewer');
const css = `${interactiveViewerCss}\n${editorCss}`;

const outPath = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'styles.generated.ts');
const banner =
  '// AUTO-GENERATED by scripts/generate-styles.mjs — do not edit by hand.\n' +
  '// Concatenated compiled CSS of @d3-polytree/interactive-viewer + @d3-polytree/editor,\n' +
  '// inlined into the <d3-polytree-editor> shadow root.\n';
writeFileSync(outPath, `${banner}export const shadowCss = ${JSON.stringify(css)};\n`);

console.log(`generate-styles: wrote ${outPath} (${css.length} bytes)`);
