// Build-time generator: bundles every SVG under src/svg/ into a typed icon map.
// Add an icon by dropping its .svg into src/svg/ (or promote one from catalog/)
// and re-running `pnpm --filter @d3-polytree/icons-amazon generate`.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const svgDir = join(here, '..', 'src', 'svg');
const outFile = join(here, '..', 'src', 'icons.generated.ts');

const files = readdirSync(svgDir)
  .filter((f) => f.endsWith('.svg'))
  .sort();

const entries = files
  .map((file) => {
    const key = file.replace(/\.svg$/, '');
    const svg = readFileSync(join(svgDir, file), 'utf8').trim();
    return `  ${JSON.stringify(key)}: ${JSON.stringify(svg)}`;
  })
  .join(',\n');

const content =
  `/* AUTO-GENERATED by scripts/generate-icons.mjs — do not edit by hand. */\n` +
  `/* Regenerate with: pnpm --filter @d3-polytree/icons-amazon generate */\n\n` +
  `export const awsIcons: Record<string, string> = {\n${entries}\n};\n`;

writeFileSync(outFile, content);
console.log(`Generated ${files.length} AWS icons -> src/icons.generated.ts`);
