// Build-time generator: emits typed PFDN document interfaces + a schema descriptor
// table from src/pfdn.json, consumed by the hand-written JSON adapter/validator in
// src/json.ts. Regenerate with `pnpm --filter @d3-polytree/pfdn-moddle generate`
// (the `build` script runs it first). Node stdlib only — no dependencies.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const schemaPath = join(here, '..', 'src', 'pfdn.json');
const outFile = join(here, '..', 'src', 'pfdn.generated.ts');

const pkg = JSON.parse(readFileSync(schemaPath, 'utf8'));
const PREFIX = pkg.prefix;
const BUILTINS = new Set(['String', 'Boolean', 'Integer', 'Real']);

const byName = new Map(pkg.types.map((t) => [t.name, t]));
const isSimple = (type) => BUILTINS.has(type);
const prefixed = (type) => (isSimple(type) ? type : `${PREFIX}:${type}`);

/** Full property list (super-first, own definitions override inherited by name). */
function resolveProps(type) {
  const acc = [];
  const seen = new Map();
  const add = (props) => {
    for (const p of props) {
      if (p.isVirtual) continue;
      if (seen.has(p.name)) acc[seen.get(p.name)] = p;
      else {
        seen.set(p.name, acc.length);
        acc.push(p);
      }
    }
  };
  for (const sc of type.superClass || []) add(resolveProps(byName.get(sc)));
  add(type.properties || []);
  return acc;
}

/** Self + all ancestors, in prefixed runtime form (drives assignability). */
function allTypes(type) {
  const out = [prefixed(type.name)];
  for (const sc of type.superClass || []) {
    for (const t of allTypes(byName.get(sc))) if (!out.includes(t)) out.push(t);
  }
  return out;
}

const tsScalar = (type) =>
  type === 'String' ? 'string' : type === 'Boolean' ? 'boolean' : 'number';
const tsType = (p) => {
  let base;
  if (p.isReference) base = 'string';
  else if (isSimple(p.type)) base = tsScalar(p.type);
  else base = `Pfdn${p.type}`;
  return p.isMany ? `${base}[]` : base;
};

const concrete = pkg.types.filter((t) => !t.isAbstract);

const interfaces = concrete
  .map((t) => {
    const lines = [`  $type: '${prefixed(t.name)}';`];
    for (const p of resolveProps(t)) lines.push(`  ${p.name}?: ${tsType(p)};`);
    return `export interface Pfdn${t.name} {\n${lines.join('\n')}\n}`;
  })
  .join('\n\n');

const elementUnion = concrete.map((t) => `Pfdn${t.name}`).join(' | ');

const propInfo = (p) =>
  `{ name: '${p.name}', type: '${prefixed(p.type)}', ` +
  `isMany: ${!!p.isMany}, isReference: ${!!p.isReference}, isId: ${!!p.isId}, isSimple: ${isSimple(p.type)} }`;

const schemaEntries = pkg.types
  .map((t) => {
    const props = resolveProps(t).map(propInfo);
    const all = allTypes(t)
      .map((n) => `'${n}'`)
      .join(', ');
    const propsBlock = props.length ? `[\n      ${props.join(',\n      ')}\n    ]` : '[]';
    return (
      `  '${prefixed(t.name)}': {\n` +
      `    abstract: ${!!t.isAbstract},\n` +
      `    allTypesByName: [${all}],\n` +
      `    properties: ${propsBlock}\n` +
      `  }`
    );
  })
  .join(',\n');

const concreteList = concrete.map((t) => `'${prefixed(t.name)}'`).join(', ');

const content =
  `/* AUTO-GENERATED by scripts/generate-pfdn.mjs — do not edit by hand. */\n` +
  `/* Regenerate with: pnpm --filter @d3-polytree/pfdn-moddle generate */\n\n` +
  `${interfaces}\n\n` +
  `/** The root PFDN document (a \`pfdn:Diagram\`) as plain JSON. */\n` +
  `export type PfdnDocument = PfdnDiagram;\n\n` +
  `/** Any concrete PFDN element, discriminated by its \`$type\`. */\n` +
  `export type PfdnElement = ${elementUnion};\n\n` +
  `export interface PropInfo {\n` +
  `  name: string;\n` +
  `  type: string;\n` +
  `  isMany: boolean;\n` +
  `  isReference: boolean;\n` +
  `  isId: boolean;\n` +
  `  isSimple: boolean;\n` +
  `}\n\n` +
  `export interface TypeInfo {\n` +
  `  abstract: boolean;\n` +
  `  allTypesByName: string[];\n` +
  `  properties: PropInfo[];\n` +
  `}\n\n` +
  `/** Per-type descriptor distilled from pfdn.json — the validator's source of truth. */\n` +
  `export const SCHEMA: Record<string, TypeInfo> = {\n${schemaEntries}\n};\n\n` +
  `/** The instantiable (non-abstract) \`$type\` values. */\n` +
  `export const CONCRETE_TYPES: string[] = [${concreteList}];\n`;

writeFileSync(outFile, content);
console.log(`Generated ${concrete.length} PFDN document types -> src/pfdn.generated.ts`);
