/* AUTO-GENERATED by scripts/generate-pfdn.mjs — do not edit by hand. */
/* Regenerate with: pnpm --filter @d3-polytree/pfdn-moddle generate */

export interface PfdnProperty {
  $type: 'pfdn:Property';
  status?: number;
  name?: string;
  type?: string;
  value?: string;
}

export interface PfdnPropertiesSet {
  $type: 'pfdn:PropertiesSet';
  status?: number;
  id?: string;
  property?: PfdnProperty[];
}

export interface PfdnCoordinates {
  $type: 'pfdn:Coordinates';
  x?: number;
  y?: number;
}

export interface PfdnZoom {
  $type: 'pfdn:Zoom';
  status?: number;
  offset?: PfdnCoordinates;
  scale?: number;
}

export interface PfdnGrid {
  $type: 'pfdn:Grid';
  show?: boolean;
  lineColor?: string;
  size?: number;
  lineWidth?: number;
}

export interface PfdnSettings {
  $type: 'pfdn:Settings';
  status?: number;
  id?: string;
  name?: string;
  author?: string;
  backgroundColor?: string;
  zoom?: PfdnZoom;
  grid?: PfdnGrid;
}

export interface PfdnLabel {
  $type: 'pfdn:Label';
  status?: number;
  id?: string;
  name?: string;
  position?: PfdnCoordinates;
  isReadOnly?: boolean;
  text?: string;
  color?: string;
  fontSize?: number;
}

export interface PfdnNode {
  $type: 'pfdn:Node';
  status?: number;
  id?: string;
  name?: string;
  label?: string;
  type?: string;
  tag?: string;
  propertiesSet?: string;
  position?: PfdnCoordinates;
  size?: number;
}

export interface PfdnBorder {
  $type: 'pfdn:Border';
  lineWidth?: number;
  lineColor?: string;
}

export interface PfdnZone {
  $type: 'pfdn:Zone';
  status?: number;
  id?: string;
  name?: string;
  label?: string;
  position?: PfdnCoordinates;
  width?: number;
  height?: number;
  fillColor?: string;
  opacity?: number;
  border?: PfdnBorder;
}

export interface PfdnLink {
  $type: 'pfdn:Link';
  status?: number;
  id?: string;
  name?: string;
  label?: string;
  source?: string;
  target?: string;
  lineColor?: string;
  lineWidth?: number;
  fillColor?: string;
  waypoint?: PfdnCoordinates[];
  pinned?: boolean;
  tag?: string;
  propertiesSet?: string;
}

export interface PfdnDiagram {
  $type: 'pfdn:Diagram';
  status?: number;
  id?: string;
  name?: string;
  settings?: PfdnSettings;
  node?: PfdnNode[];
  link?: PfdnLink[];
  label?: PfdnLabel[];
  zone?: PfdnZone[];
  propertiesSet?: PfdnPropertiesSet[];
}

/** The root PFDN document (a `pfdn:Diagram`) as plain JSON. */
export type PfdnDocument = PfdnDiagram;

/** Any concrete PFDN element, discriminated by its `$type`. */
export type PfdnElement = PfdnProperty | PfdnPropertiesSet | PfdnCoordinates | PfdnZoom | PfdnGrid | PfdnSettings | PfdnLabel | PfdnNode | PfdnBorder | PfdnZone | PfdnLink | PfdnDiagram;

export interface PropInfo {
  name: string;
  type: string;
  isMany: boolean;
  isReference: boolean;
  isId: boolean;
  isSimple: boolean;
}

export interface TypeInfo {
  abstract: boolean;
  allTypesByName: string[];
  properties: PropInfo[];
}

/** Per-type descriptor distilled from pfdn.json — the validator's source of truth. */
export const SCHEMA: Record<string, TypeInfo> = {
  'pfdn:Statusable': {
    abstract: true,
    allTypesByName: ['pfdn:Statusable'],
    properties: [
      { name: 'status', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true }
    ]
  },
  'pfdn:Base': {
    abstract: true,
    allTypesByName: ['pfdn:Base', 'pfdn:Statusable'],
    properties: [
      { name: 'status', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'id', type: 'String', isMany: false, isReference: false, isId: true, isSimple: true },
      { name: 'name', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true }
    ]
  },
  'pfdn:Property': {
    abstract: false,
    allTypesByName: ['pfdn:Property', 'pfdn:Statusable'],
    properties: [
      { name: 'status', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'name', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'type', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'value', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true }
    ]
  },
  'pfdn:PropertiesSet': {
    abstract: false,
    allTypesByName: ['pfdn:PropertiesSet', 'pfdn:Statusable'],
    properties: [
      { name: 'status', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'id', type: 'String', isMany: false, isReference: false, isId: true, isSimple: true },
      { name: 'property', type: 'pfdn:Property', isMany: true, isReference: false, isId: false, isSimple: false }
    ]
  },
  'pfdn:Coordinates': {
    abstract: false,
    allTypesByName: ['pfdn:Coordinates'],
    properties: [
      { name: 'x', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'y', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true }
    ]
  },
  'pfdn:Zoom': {
    abstract: false,
    allTypesByName: ['pfdn:Zoom', 'pfdn:Statusable'],
    properties: [
      { name: 'status', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'offset', type: 'pfdn:Coordinates', isMany: false, isReference: false, isId: false, isSimple: false },
      { name: 'scale', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true }
    ]
  },
  'pfdn:Grid': {
    abstract: false,
    allTypesByName: ['pfdn:Grid'],
    properties: [
      { name: 'show', type: 'Boolean', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'lineColor', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'size', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'lineWidth', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true }
    ]
  },
  'pfdn:Settings': {
    abstract: false,
    allTypesByName: ['pfdn:Settings', 'pfdn:Base', 'pfdn:Statusable'],
    properties: [
      { name: 'status', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'id', type: 'String', isMany: false, isReference: false, isId: true, isSimple: true },
      { name: 'name', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'author', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'backgroundColor', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'zoom', type: 'pfdn:Zoom', isMany: false, isReference: false, isId: false, isSimple: false },
      { name: 'grid', type: 'pfdn:Grid', isMany: false, isReference: false, isId: false, isSimple: false }
    ]
  },
  'pfdn:Label': {
    abstract: false,
    allTypesByName: ['pfdn:Label', 'pfdn:Base', 'pfdn:Statusable'],
    properties: [
      { name: 'status', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'id', type: 'String', isMany: false, isReference: false, isId: true, isSimple: true },
      { name: 'name', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'position', type: 'pfdn:Coordinates', isMany: false, isReference: false, isId: false, isSimple: false },
      { name: 'isReadOnly', type: 'Boolean', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'text', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'color', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'fontSize', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true }
    ]
  },
  'pfdn:Node': {
    abstract: false,
    allTypesByName: ['pfdn:Node', 'pfdn:Base', 'pfdn:Statusable'],
    properties: [
      { name: 'status', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'id', type: 'String', isMany: false, isReference: false, isId: true, isSimple: true },
      { name: 'name', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'label', type: 'pfdn:Label', isMany: false, isReference: true, isId: false, isSimple: false },
      { name: 'type', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'tag', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'propertiesSet', type: 'pfdn:PropertiesSet', isMany: false, isReference: true, isId: false, isSimple: false },
      { name: 'position', type: 'pfdn:Coordinates', isMany: false, isReference: false, isId: false, isSimple: false },
      { name: 'size', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true }
    ]
  },
  'pfdn:Border': {
    abstract: false,
    allTypesByName: ['pfdn:Border'],
    properties: [
      { name: 'lineWidth', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'lineColor', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true }
    ]
  },
  'pfdn:Zone': {
    abstract: false,
    allTypesByName: ['pfdn:Zone', 'pfdn:Base', 'pfdn:Statusable'],
    properties: [
      { name: 'status', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'id', type: 'String', isMany: false, isReference: false, isId: true, isSimple: true },
      { name: 'name', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'label', type: 'pfdn:Label', isMany: false, isReference: true, isId: false, isSimple: false },
      { name: 'position', type: 'pfdn:Coordinates', isMany: false, isReference: false, isId: false, isSimple: false },
      { name: 'width', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'height', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'fillColor', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'opacity', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'border', type: 'pfdn:Border', isMany: false, isReference: false, isId: false, isSimple: false }
    ]
  },
  'pfdn:Link': {
    abstract: false,
    allTypesByName: ['pfdn:Link', 'pfdn:Base', 'pfdn:Statusable'],
    properties: [
      { name: 'status', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'id', type: 'String', isMany: false, isReference: false, isId: true, isSimple: true },
      { name: 'name', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'label', type: 'pfdn:Label', isMany: false, isReference: true, isId: false, isSimple: false },
      { name: 'source', type: 'String', isMany: false, isReference: true, isId: false, isSimple: true },
      { name: 'target', type: 'String', isMany: false, isReference: true, isId: false, isSimple: true },
      { name: 'lineColor', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'lineWidth', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'fillColor', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'waypoint', type: 'pfdn:Coordinates', isMany: true, isReference: false, isId: false, isSimple: false },
      { name: 'pinned', type: 'Boolean', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'tag', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'propertiesSet', type: 'pfdn:PropertiesSet', isMany: false, isReference: true, isId: false, isSimple: false }
    ]
  },
  'pfdn:Diagram': {
    abstract: false,
    allTypesByName: ['pfdn:Diagram', 'pfdn:Base', 'pfdn:Statusable'],
    properties: [
      { name: 'status', type: 'Real', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'id', type: 'String', isMany: false, isReference: false, isId: true, isSimple: true },
      { name: 'name', type: 'String', isMany: false, isReference: false, isId: false, isSimple: true },
      { name: 'settings', type: 'pfdn:Settings', isMany: false, isReference: false, isId: false, isSimple: false },
      { name: 'node', type: 'pfdn:Node', isMany: true, isReference: false, isId: false, isSimple: false },
      { name: 'link', type: 'pfdn:Link', isMany: true, isReference: false, isId: false, isSimple: false },
      { name: 'label', type: 'pfdn:Label', isMany: true, isReference: false, isId: false, isSimple: false },
      { name: 'zone', type: 'pfdn:Zone', isMany: true, isReference: false, isId: false, isSimple: false },
      { name: 'propertiesSet', type: 'pfdn:PropertiesSet', isMany: true, isReference: false, isId: false, isSimple: false }
    ]
  }
};

/** The instantiable (non-abstract) `$type` values. */
export const CONCRETE_TYPES: string[] = ['pfdn:Property', 'pfdn:PropertiesSet', 'pfdn:Coordinates', 'pfdn:Zoom', 'pfdn:Grid', 'pfdn:Settings', 'pfdn:Label', 'pfdn:Node', 'pfdn:Border', 'pfdn:Zone', 'pfdn:Link', 'pfdn:Diagram'];
